name: GitHub Actions Project Cloud

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    strategy:
      matrix:
        node-version: [16.x]
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

    # logout in case allready loged
    - run: docker logout
    - run: docker  build --no-cache -t sysinfo-api:0.0.2 . 
    
    - run: docker tag sysinfo-api:0.0.2 $DOCKER_USER/sysinfo-api:0.0.2
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - run: docker push $DOCKER_USER/sysinfo-api:0.0.2